//This file was generated by CMake.
#include <QString>
/**
 * @brief Get the version of ff7tk in use
 * @return: Version of ff7tk
*/
QString ff7tk_version() {
    return QStringLiteral("0.80.21");
}

/**
 * @brief Get the checked out revision of the ff7tk in use
 * @return: Revision of ff7tk if build from checked out Git repo
*/
QString ff7tk_revision() {
    QString revision = QStringLiteral("7cd380a");
    if(!QString("7cd380a").isEmpty())
        revision.prepend(QStringLiteral("."));
    return revision;
}

/**
 * @brief Get the major version of Qt that was used to build ff7tk
 * @return: Qt5 or Qt6 depending on what library was used to build ff7tk
*/
QString ff7tk_qt_version() {
    return QStringLiteral("Qt%1").arg(QStringLiteral("6"));
}
